name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: Install dependencies
        run: npm install
      - name: run Lighthouse CI
        run: |
          npm i -g @lhci/cli 
          lhci autorun --config=/.lighthouserc-cli.js
  